version: '3'

services:
  srt2rtmp:
    image: eyevinntechnology/toolbox-srt2rtmp:0.1.0
    restart: unless-stopped

    ports:
      - "1234:1234/udp"
    command: "0.0.0.0:1234 rtmp://ingest.videoflow.io/live/srt2rtmp"
